### PR TITLE
make organisation id optional in GetPatient list

### LINKED ISSUE #341: GetPatientList Organization ID not optional
### Describe the bug

```proto
message GetPatientListRequest {
  string organisation_id = 1;
}
```

### Describe how to produce the bug

try to get the patientlist with the default organisation (no organization id in request)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by DasProffi**
## Which issues does this pull request close?
closes #341

### CODE REVIEW

File: services/task-svc/internal/repositories/patient_repository.go [hunk 1]
```diff
@@ -83,7 +83,8 @@ func (r *PatientRepository) GetUnassignedPatientsForOrganization(organizationID
 func (r *PatientRepository) GetDischargedPatientsForOrganization(organizationID uuid.UUID) ([]models.Patient, error) {
 	var patients []models.Patient
 	query := r.db.
-		Where("organization_id = ? AND is_discharged = 1", organizationID).
+		Unscoped().
+		Where("organization_id = ? AND NOT is_discharged = 0", organizationID).
```
Comment (MaxSchaefer) [inline services/task-svc/internal/repositories/patient_repository.go:87]: Why did you negate this condition, and why is this change in the scope of this pull request?

**Review by MaxSchaefer — CHANGES_REQUESTED** [review]

File: services/task-svc/internal/repositories/patient_repository.go (hunk 1 above)
Comment (DasProffi) [reply services/task-svc/internal/repositories/patient_repository.go:87]: because the request didn't return any discharged patients, because we need the unscoped to see the soft deleted entries.
The `NOT is_discharged = 0` is there, because the softdelete is a timestamp and any value that isn't the default (not deleted) indicates deletion. Thus checking `discharged = 0` might not work properly

**Review by MaxSchaefer — APPROVED** [review]
